# Generated by Django 3.2.9 on 2021-12-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canyon_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canyon_name', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=8)),
                ('length', models.CharField(max_length=15)),
                ('gear', models.CharField(max_length=255)),
                ('rappels', models.CharField(max_length=255)),
                ('water', models.CharField(max_length=255)),
                ('flashflood', models.CharField(max_length=255)),
                ('access', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
