# Generated by Django 3.2.9 on 2021-12-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canyoneering_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='canyon_details',
            name='comment',
        ),
    ]
