# Generated by Django 3.2.9 on 2021-12-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canyoneering_app', '0002_auto_20211215_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='canyon_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canyon', to='canyoneering_app.user'),
        ),
    ]
