# Generated by Django 3.2.9 on 2021-12-21 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canyoneering_app', '0009_auto_20211221_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canyon_details',
            name='user',
            field=models.ManyToManyField(related_name='canyon', to=settings.AUTH_USER_MODEL),
        ),
    ]
