# Generated by Django 3.2.9 on 2022-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canyoneering_app', '0010_alter_canyon_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='canyon_details',
            name='latitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='canyon_details',
            name='longitude',
            field=models.CharField(default='', max_length=10),
        ),
    ]
